import { Type } from '@google/genai';

const nullableString = { type: Type.STRING, nullable: true } as const;
const stringArray = { type: Type.ARRAY, items: { type: Type.STRING } } as const;

/**
 * Schema de saída (estilo OpenAPI) entregue ao Gemini via `responseSchema`.
 * Mantido separado do schema Zod (que é defensivo, com transforms/catch que não
 * são representáveis em JSON Schema).
 */
export const RGP_RESPONSE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    tipo_pessoa: { type: Type.STRING, enum: ['PF', 'PJ'] },

    numero_processo: nullableString,
    ato_administrativo_concedente: nullableString,
    numero_rgp: nullableString,
    codigo_frota: nullableString,
    inscricao_autoridade_naval: nullableString,

    nome_embarcacao: nullableString,
    ano_construcao: nullableString,
    numero_tripulantes: nullableString,
    comprimento_m: nullableString,
    arqueacao_bruta: nullableString,
    potencia_motor_hp: nullableString,
    material_casco: nullableString,
    propulsao: nullableString,
    tipo_combustivel: nullableString,

    metodo: nullableString,
    petrecho: nullableString,
    especie_alvo: stringArray,
    fauna_acompanhante: stringArray,
    autorizacao_complementar: stringArray,
    area_atuacao: stringArray,

    nome: nullableString,
    cpf: nullableString,
    razao_social: nullableString,
    cnpj: nullableString,
    nome_representante_legal: nullableString,
    cpf_representante_legal: nullableString,

    endereco: nullableString,
    bairro: nullableString,
    cidade_uf: nullableString,

    data_inicio_validade: nullableString,
    data_termino_validade: nullableString,
  },
  required: [
    'tipo_pessoa',
    'numero_processo',
    'ato_administrativo_concedente',
    'numero_rgp',
    'codigo_frota',
    'inscricao_autoridade_naval',
    'nome_embarcacao',
    'ano_construcao',
    'numero_tripulantes',
    'comprimento_m',
    'arqueacao_bruta',
    'potencia_motor_hp',
    'material_casco',
    'propulsao',
    'tipo_combustivel',
    'metodo',
    'petrecho',
    'especie_alvo',
    'fauna_acompanhante',
    'autorizacao_complementar',
    'area_atuacao',
    'nome',
    'cpf',
    'razao_social',
    'cnpj',
    'nome_representante_legal',
    'cpf_representante_legal',
    'endereco',
    'bairro',
    'cidade_uf',
    'data_inicio_validade',
    'data_termino_validade',
  ],
  propertyOrdering: [
    'tipo_pessoa',
    'numero_processo',
    'ato_administrativo_concedente',
    'numero_rgp',
    'codigo_frota',
    'inscricao_autoridade_naval',
    'nome_embarcacao',
    'ano_construcao',
    'numero_tripulantes',
    'comprimento_m',
    'arqueacao_bruta',
    'potencia_motor_hp',
    'material_casco',
    'propulsao',
    'tipo_combustivel',
    'metodo',
    'petrecho',
    'especie_alvo',
    'fauna_acompanhante',
    'autorizacao_complementar',
    'area_atuacao',
    'nome',
    'cpf',
    'razao_social',
    'cnpj',
    'nome_representante_legal',
    'cpf_representante_legal',
    'endereco',
    'bairro',
    'cidade_uf',
    'data_inicio_validade',
    'data_termino_validade',
  ],
} as any;
